fix make_nr if no dups exist
the branch for the case that no duplicates exist
fails because is assumes that the input is a
single file:

```
Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/peterjc/make_nr/c84f12187af9/make_nr/tools/make_nr/make_nr.py", line 133, in <module>
    make_nr(args, options.output, options.sep, options.alphasort)
  File "/gpfs1/data/galaxy_server/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/peterjc/make_nr/c84f12187af9/make_nr/tools/make_nr/make_nr.py", line 128, in make_nr
    os.symlink(os.path.abspath(input_fasta), output_fasta)
  File "/gpfs1/data/galaxy_server/galaxy/database/dependencies/_conda/envs/__biopython@1.67/lib/python3.6/posixpath.py", line 378, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not list
```